language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
    include:
      - python: 2.7
      - python: 3.4
      - python: 3.6
      - python: 3.7
      - python: 3.8
      - python: pypy
      - python: 3.7
        env: TOXENV=flake8

install:
  - pip install tox-travis

script:
  - tox
