name: Run checks

on: [push, pull_request]

jobs:
  tox:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-latest", "macos-latest", "windows-latest"]
        environment: ["py27", "py34", "py35", "py36", "py37", "flake8"]
        
        include:
          - environment: "py27"
            python: "2.7"
          - environment: "py34"
            python: "3.4"
          - environment: "py35"
            python: "3.5"
          - environment: "py36"
            python: "3.6"
          - environment: "py37"
            python: "3.7"
          - environment: "flake8"
            python: "3.7"

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Run tox
      run: |
        tox -e ${{ matrix.environment }}
