name: Run checks

on: [push, pull_request]

jobs:
  tox:
    strategy:
      matrix:
        platform: ["ubuntu-latest", "macos-latest", "windows-latest"]
        environment: ["py36", "py37", "flake8", "mypy"]
        
        include:
          - environment: "py36"
            python: "3.6"
          - environment: "py37"
            python: "3.7"
          - environment: "flake8"
            python: "3.7"
          - environment: "mypy"
            python: "3.7"

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Run tox
      run: |
        tox -e ${{ matrix.environment }}
